apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresql 
  name: pvc-postgresql
spec:
  resources:
    requests:
      storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
