apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  "provisioning/datasources/prometheus.yaml": |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
  "provisioning/dashboards/default.yaml": |
    apiVersion: 1
    providers:
      - name: 'Default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/dashboards
  "dashboards/coin_metrics.json": |
    {
      "annotations": {
        "list": []
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "PBFA97CFB590B2093"
          },
          "fieldConfig": {
            "defaults": {
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": []
              },
              "unit": "none"
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "title": "Coin Flips",
          "type": "stat",
          "targets": [
            {
              "expr": "heads_counter",
              "legendFormat": "Heads"
            },
            {
              "expr": "tails_counter",
              "legendFormat": "Tails"
            },
            {
              "expr": "flip_coins_total",
              "legendFormat": "Total Flips"
            }
          ]
        }
      ],
      "refresh": "5s",
      "schemaVersion": 38,
      "style": "dark",
      "title": "Coin iFlip Metrics",
      "version": 1
    } 