apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  labels:
    app: fastapi-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  type: LoadBalancer
  selector:
    app: fastapi-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: debug
      port: 5678
      targetPort: 5678
      nodePort: 30078
