apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-coin-client-deployment
  labels:
    app: mock-coin-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-coin-client
  template:
    metadata:
      labels:
        app: mock-coin-client
    spec:
      containers:
      - name: mock-coin-client
        image: artiseasy/mock-coin-client:latest
        # imagePullPolicy: Never
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: FASTAPI_SERVICE_URL
          value: "http://fastapi-app-service:8000"