apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-app
spec:
  type: LoadBalancer
  selector:
    app: grafana-app
  ports:
    - port: 3000
      targetPort: 3000
